name: i18n-check
on:
  # pull_request_target is needed instead of just pull_request
  # because secret is needed to sync with weblate
  # Attention! Read more at https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests
  pull_request_target:
    branches:
      main

jobs:
  i18n-check-run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check i18n
        uses: dgaponov/weblate-action@v1.26
        with:
            SERVER_URL: "http://158.160.122.254"
            TOKEN: ${{ secrets.WEBLATE_TOKEN }}
            PROJECT: "datalens"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
